owner: rollerozxa
repo: uptime-test

sites:
  - name: principia-web
    url: https://principia-web.se
    maxResponseTime: 1500
  - name: principia-web-archive
    url: https://archive.principia-web.se
    maxResponseTime: 1500

  - name: voxelmanip.se
    url: https://voxelmanip.se
    maxResponseTime: 1500
  - name: Voxelmanip Forums
    url: https://forum.voxelmanip.se
    maxResponseTime: 1500

status-website:
  cname: status.voxelmanip.se
  name: ROllerozxa uptime status
  introTitle: ROllerozxa uptime status
  introMessage: This status page tracks the uptime for services hosted by ROllerozxa.
  navbar:
    - title: Status
      href: /

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
